- name: Copy the private key to ssh folder
  amazon.aws.ssm_parameter:
    name: {{ github_key_paramater_name }}
    with_decryption: yes
    region: "us-east-1"
  register: github_key

- name: Copy SSH private key
  copy:
    content: "{{ github_key }}"
    dest: "{{ ansible_user_dir }}/.ssh/github_key"
    mode: "0600"

- name: Create ssh config for github authentication
  template:
    src: "templates/ssh_config.j2"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: "0644"