- name: Enable jenkins
  systemd:
      name: jenkins
      state: started
      enabled: yes

- name: Get password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: Print password
  debug:
    msg:
      - Jenkins Installation Completed
      - ADMIN PASSWORD : {{jenkins_password.stdout}}
