pipeline {
    agent any
    
    tools {
          maven 'maven'
        }
        
    environment {
          scanner = tool 'sonarscanner'
        }
        
    stages {
        stage('checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sai-harsha-dev/Boardgame.git'
            }
        }
        
        stage('package') {
            steps {
                sh '''mvn package
                      mvn dependency:copy-dependencies'''
            }
        }
        
        stage('scan') {
            steps {
                withSonarQubeEnv('sonarserver') {
                    sh '''$scanner/bin/sonar-scanner \
                        -Dsonar.projectName=test \
                        -Dsonar.java.binaries=target
                        -Dsonar.java.libraries=target/dependency/*.jar'''
                }
            }
        }

        stage('wait for QG'){
            steps{
                timeout(5) {
                    waitForQualityGate abortPipeline: false
                }
                echo "Quality gate passed"
            }
        }
    }
}