pipeline {
    agent any
    
    tools {
          maven 'maven'
        }
        
    environment {
          scanner = tool 'sonarscanner'
        }
        
    stages {
        stage('checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sai-harsha-dev/Boardgame.git'
            }
        }
        
        stage('package') {
            steps {
                sh '''mvn package
                      mvn dependency:copy-dependencies'''
            }
        }
        
        stage('scan') {
            steps {
                withSonarQubeEnv('sonarserver') {
                    sh '''jars=$(find target/dependency -name "*.jar" | paste -sd "," -)

                        cat <<EOF > sonar-scanner.properties
sonar.projectKey=test
sonar.projectName=test
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.libraries=$jars
EOF
                        
                        $scanner/bin/sonar-scanner \
                        -Dproject.settings=sonar-scanner.properties
                        '''
                }
            }
        }

        stage('wait for QG'){
            steps{
                timeout(5) {
                    waitForQualityGate abortPipeline: false
                }
                echo "Quality gate passed"
            }
        }
    }
}